[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "get_a_wai"
version = "0.1.0"
dependencies = [
    "bs4",
    "Flask",
    "requests",
]
requires-python = ">=3.8"
